#!/usr/bin/python

bnchmrk="classify"
benchmark="Feature Based Classification"
checkProgram="../bench/classifyCheck"
dataDir = "../sequenceData/data"

tests = [
]

import sys
sys.path.insert(0, 'common')
import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

