#!/usr/bin/python

bnchmrk="MST"
benchmark="Minimum Spanning Tree"
checkProgram="../bench/MSTCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_WE_5_4000000", "", ""],
    [1, "rMatGraph_WE_10_2000000", "", ""],
    [1, "2Dgrid_WE_6440000", "", ""]
    ]

import sys
sys.path.insert(0, 'common')
import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

