include parlayKNNG/common/parallelDefs

BENCH = neighbors
REQUIRE = 

include parlayKNNG/common/MakeBench


all:
	@echo "*--------------------------------*"
	@echo "| Welcome to STANN!  See         |"
	@echo "| README.txt in NearestNeighbors |"
	@echo "| for information on usage.      |"
	@echo "|                                |"
	@echo "| The default compiled version   |"
	@echo "| is parlayKNNG. Compile in the  |"
	@echo "| specific folder if you don't   |"
	@echo "| want to see this message each  |"
	@echo "| time you compile               |"
	@echo "*--------------------------------*"



