#!/usr/bin/python

bnchmrk="matching"
benchmark="Maximal Matching"
checkProgram="../bench/matchingCheck"
dataDir = "../graphData/data"

tests = [
    [1, "randLocalGraph_E_5_4000000", "", ""],
    [1, "rMatGraph_E_10_2000000", "", ""],
    [1, "2Dgrid_E_6440000", "", ""]
    ]

import sys
sys.path.insert(0, 'common')
import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

