#!/usr/bin/python

bnchmrk="neighbors"
benchmark="Nearest Neighbors"
checkProgram="../bench/neighborsCheck"
dataDir = "../geometryData/data"

tests = [    
    [1, "2DinCube_10000000","-d 2 -k 1", "-d 2 -k 1"],
    [1, "2Dkuzmin_10000000","-d 2 -k 1", "-d 2 -k 1"],
    
    [1, "3DinCube_10000000","-d 3 -k 1", "-d 3 -k 1"],
    [1, "3DonSphere_10000000","-d 3 -k 1", "-d 3 -k 1"],

    [1, "3DinCube_10000000","-d 3 -k 10", "-d 3 -k 10"],
    [1, "3Dplummer_10000000","-d 3 -k 10", "-d 3 -k 10"]
    ]

import sys
sys.path.insert(0, 'common')
import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

