#!/usr/bin/python

bnchmrk="bw"
benchmark="Burrows Wheeler"
checkProgram="../bench/bwCheck"
dataDir = "../sequenceData/data"

tests = [
    [1, "trigramString_250000000", "", ""],
    [1, "randomSeq_30000000_int", "", ""],
    [1, "etext99", "", ""],
    [1, "wikipedia250M.txt", "", ""]
]

import sys
sys.path.insert(0, 'common')
import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

